<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<?php if (!empty($categories)): ?>

<form data-group="announce">
	<div class="well">

        <?php echo Element::hidden('announce[id]', $announce->getId()); ?>
        <?php echo Element::hidden('announce[web_page_id]', $announce->getWebPageId()); ?>
        <?php echo Element::hidden('web_page_id', $announce->getWebPageId()); ?>
        
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group date">
                    <?php echo Element::text('announce[name]', $announce->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name of this announce'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil" data-toggle="tooltip"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::select('announce[category_id]', $categories, $announce->getCategoryId(), array('class' => 'form-control')); ?>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('announce[intro]', $announce->getIntro(), array('data-wysiwyg' => 'true')); ?>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('announce[full]', $announce->getFull(), array('data-wysiwyg' => 'true')); ?>
			</div>
		</div>
		
		<div class="options">
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
                    <?php echo Element::checkbox('announce[published]', $announce->getPublished(), array('class' => 'form-control')); ?>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
				<div class="col-lg-10">
                    <?php echo Element::checkbox('announce[seo]', $announce->getSeo(), array('class' => 'form-control')); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Icon'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
                        <?php echo Element::text('announce[icon]', $announce->getIcon(), array('class' => 'form-control', 'placeholder' => $this->translate('Path to the icon for this announce'))); ?>
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
                        <?php echo Element::number('announce[order]', $announce->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Order of the announce to be created'))); ?>
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
                        <?php echo Element::text('announce[slug]', $announce->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this announce. By default is taken from a title'))); ?>
						<span class="input-group-addon">
							<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh'); ?>"></i></a>
						</span>
					</div>
				</div>
			</div>
            
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('announce[title]', $announce->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Announce title'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
			
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
				<div class="col-lg-10">
                    <?php echo Element::textarea('announce[keywords]', $announce->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-lg-2 control-label"><?php $this->show('Meta-Description'); ?></label>
				<div class="col-lg-10">
                    <?php echo Element::textarea('announce[meta_description]', $announce->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
				</div>
			</div>
		</div>
	</div>

	<?php if ($announce->getId()): ?>

    <button data-button="save" data-url="<?php echo $this->url('Announcement:Admin:Announce@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Announcement:Admin:Announce@addAction'); ?>" data-url="<?php echo $this->url('Announcement:Admin:Announce@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>

    <?php else: ?>

    <button data-button="add" data-back-url="<?php echo $this->url('Announcement:Admin:Announce@editAction', null); ?>" data-url="<?php echo $this->url('Announcement:Admin:Announce@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Announcement:Admin:Announce@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Add & Create new'); ?></button>

    <?php endif; ?>

	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" data-url="<?php echo $this->url('Announcement:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>

<?php else: ?>

<div class="well">
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to add a new announce, you have to create at least on category'); ?></h2>
	</div>
</div>

<?php endif; ?>