<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;
?>

<?php if (!empty($categories)): ?>

<form class="card" data-group="announce" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Announcement'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?php echo $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">

                    <?php $entity = LanguageManager::findByLangId($language->getId(), $announce); ?>

                    <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group date">
                                <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Name of this announce'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil" data-toggle="tooltip"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::textarea(sprintf('translation[%s][intro]', $language->getId()), $entity->getIntro(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
                        <div class="col-lg-10">
                            <?php echo Element::textarea(sprintf('translation[%s][full]', $language->getId()), $entity->getFull(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'placeholder' => $this->translate('URL slug for this announce. By default its taken from the name'))); ?>

                                    <span class="input-group-addon">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label"><?php $this->show('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), array('class' => 'form-control')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), array('class' => 'form-control')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Announce title'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Meta-Description'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        
        <div role="tabpanel" class="tab-pane" id="configuration">
            <?php echo Element::hidden('announce[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::select('announce[category_id]', $categories, $entity->getCategoryId(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('announce[published]', $entity->getPublished(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('announce[seo]', $entity->getSeo(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Icon'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('announce[icon]', $entity->getIcon(), array('class' => 'form-control', 'placeholder' => $this->translate('Path to the icon for this announce'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('announce[order]', $entity->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Order of the announce to be created'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Announcement:Admin:Announce@addAction',
        'edit' => 'Announcement:Admin:Announce@editAction',
        'save' => 'Announcement:Admin:Announce@saveAction',
        'cancel' => 'Announcement:Admin:Browser@indexAction',
        'options' => true
    )); ?>

</form>

<?php else: ?>

<div class="center-block">
    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to add a new announce, you have to create at least on category'); ?></h2>
</div>

<?php endif; ?>