<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Announcement:Admin:Announce@addAction' => 'Add new announce',
            'Announcement:Admin:Category@addAction' => $extendedMode ? 'Add a category' : null
        ),

        'actions' => array(
            'data' => $announces,
            'save' => 'Announcement:Admin:Browser@tweakAction',
            'delete' => 'Announcement:Admin:Announce@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Announcements')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($announces, array(
                'pk' => 'id',
                'batch' => true,
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'category_name',
                        'label' => 'Category'
                    ),

                    array(
                        'column' => 'order',
                        'value' => function($row){
                            return Element::number(sprintf('order[%s]', $row['id']), $row['order'], array('class' => 'form-control', 'min' => '0'));
                        }
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($row){
                            return Element::checkbox(sprintf('published[%s]', $row['id']), $row['published']);
                        }
                    ),

                    array(
                        'column' => 'seo',
                        'label' => 'SEO',
                        'value' => function($row){
                            return Element::checkbox(sprintf('seo[%s]', $row['id']), $row['seo']);
                        }
                    )
                ),

                'actions' => array(
                    'view' => function($row){
                        return Icon::view($row['url'], $this->translate('View this announce'));
                    },

                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Announcement:Admin:Announce@editAction', $row['id']),
                            $this->translate('Edit this announce')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Announcement:Admin:Announce@deleteAction', $row['id']), 
                            $this->translate('Remove this announce')
                        );
                    }
                )

            ))); ?>

            <?php if (empty($announces)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No announces'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="card">
    <div class="table-responsive">
        <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

        <?= $this->widget(new GridViewWidget($categories, array(
            'tableClass' => 'table table-hover table-bordered table-striped',
            'rowAttributes' => array(
                'class' => function($row) use ($categoryId){
                    return $row['id'] == $categoryId ? 'table-info' : null;
                }
            ),
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                    'value' => function($row){
                        return Element::link($row['name'], $this->url('Announcement:Admin:Browser@categoryAction', $row['id']));
                    }
                ),

                array(
                    'column' => 'class'
                )
            ),

            'actions' => array(
                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Announcement:Admin:Category@editAction', $row['id']),
                        $this->translate('Edit this category')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Announcement:Admin:Category@deleteAction', $row['id']),
                        $this->translate('Remove this category')
                    );
                }
            )
        ))); ?>

        <?php if (empty($categories)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
        </div>
        <?php endif; ?>
    </div>
</div>
