<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Announcement:Admin:Announce@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new announce'); ?></a></li>
		 
		 <?php if ($extendedMode): ?>
		 <li><a href="<?php echo $this->url('Announcement:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add a category'); ?></a></li>
		 <?php endif; ?>
		 
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 <?php if (!empty($announces)): ?>
		 <li><a data-button="save-changes" data-url="<?php echo $this->url('Announcement:Admin:Browser@tweakAction'); ?>" href="#"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a data-button="remove-selected" data-url="<?php echo $this->url('Announcement:Admin:Announce@deleteAction', null); ?>" href="#"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<div class="row">
    <div class="col-lg-8">
        <?php $this->loadPartial('items-per-page', array('caption' => 'Announcements')); ?>

        <form>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped table-condensed">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <?php if (!empty($announces)): ?>
                                <input type="checkbox" />
                                <?php endif; ?>
                            </th>
                            <th class="text-center"><?php $this->show('#'); ?></th>
                            <th class="text-center"><?php $this->show('Name'); ?></th>
                            <th class="text-center"><?php $this->show('Category'); ?></th>
                            <th class="text-center"><?php $this->show('Order'); ?></th>
                            <th class="text-center"><?php $this->show('Published'); ?></th>
                            <th class="text-center"><?php $this->show('SEO'); ?></th>
                            <th class="text-center"><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    
                    <?php if (!empty($announces)): ?>
                    <tbody>
                        <?php foreach ($announces as $announce): ?>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="toDelete[<?php echo $announce->getId(); ?>]" />
                            </td>
                            <td class="text-center text-muted"><?php echo $announce->getId(); ?></td>
                            <td class="text-center"><?php echo $announce->getName(); ?></td>
                            <td class="text-center"><?php echo $announce->getCategoryName(); ?></td>
                            <td class="col-lg-1">
                                <?php echo Element::number(sprintf('order[%s]', $announce->getId()), $announce->getOrder(), array('class' => 'form-control', 'min' => '0')); ?>
                            </td>
                            <td class="text-center">
                                <?php echo Element::checkbox(sprintf('published[%s]', $announce->getId()), $announce->getPublished()); ?>
                            </td>
                            <td class="text-center">
                                <?php echo Element::checkbox(sprintf('seo[%s]', $announce->getId()), $announce->getSeo()); ?>
                            </td>
                            <td class="text-center">
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this announce'); ?>" data-button="view" href="<?php echo $announce->getUrl(); ?>" target="_blank" ><i class="glyphicon glyphicon-search"></i></a>
                                <a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this announce'); ?>" href="<?php echo $this->url('Announcement:Admin:Announce@editAction', $announce->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                <a data-button="delete" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this announce'); ?>" data-url="<?php echo $this->url('Announcement:Admin:Announce@deleteAction', $announce->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                            </td>
                        </tr>
                        
                        <?php endforeach; ?>
                    </tbody>
                    <?php endif; ?>
                    
                </table>
                
                <?php if (empty($announces)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No announces'); ?></h2>
                </div>
                <?php endif; ?>
            </div>
        </form>

        <?php $this->loadPartial('paginator'); ?>
    </div>

    <div class="col-lg-4">
        <div class="table-responsive">
            <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

            <?= Grid::render($categories, array(
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'rowAttributes' => array(
                    'class' => function($row) use ($categoryId){
                        return $row['id'] == $categoryId ? 'info' : null;
                    }
                ),
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name',
                        'value' => function($row){
                            return Element::link($row['name'], $this->url('Announcement:Admin:Browser@categoryAction', $row['id']));
                        }
                    ),

                    array(
                        'column' => 'class'
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Announcement:Admin:Category@editAction', $row['id']),
                            $this->translate('Edit this category')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Announcement:Admin:Category@deleteAction', $row['id']),
                            $this->translate('Remove this category')
                        );
                    }
                )

            ), $this->translator); ?>

            <?php if (empty($categories)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
