<?php

use Krystal\Form\Element;

?>

<form>
	<div class="well clearfix">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('category[class]', $category->getClass(), array('class' => 'form-control', 'placeholder' => $this->translate('Class name for rendering'))); ?>
			</div>
		</div>
	</div>

	<?php if (!$category->getId()): ?>
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>

	<?php else: ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>

	<?php endif; ?>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php echo $this->translate('Cancel'); ?></button>

</form>